config/routes.rb
Reporter::Application.routes.draw do

  namespace :v1 do
    resources :reports, only: [:create, :index, :show, :update] do
      resources :abuses, only: [:create]
      resources :opinions, only: [:create, :index, :show, :update]
    end
    resources :maps, only: [] do
      collection do
        get :border
      end
    end
    resources :categories, only: [:index]
  end

  namespace :admin do
    root to: 'reports#index'
    get 'logout', to: 'user_sessions#destroy', as: :logout
    get 'login', to: 'user_sessions#new', as: :login
    resources :user_sessions, only: [:create]
    resources :reports
    resources :opinions
    resources :abuses
    resources :categories
  end

  root to: 'home#index'
end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
  belongs_to :report

  validates_presence_of :title, :description, :report_id

  validates_format_of :title, with: /^.{3,15}$/, multiline: true
  validates_format_of :description, with: /^.{15,160}$/, multiline: true

  def rating
    positives - negatives
  end

  def rate!(key)
    increment!(key) if key.present?
  end
end

app/controllers/admin/opinions_controller.rb
# -*- encoding : utf-8 -*-
class Admin::OpinionsController < Admin::AdminController

  expose(:opinions) { Opinion.order(sort_column("Opinion") + " " + sort_direction).page(params[:page]).per(10) }
  expose(:opinion)

  rescue_from ActiveRecord::RecordNotFound, with: :no_record_handler

  def destroy
    if opinion.destroy
      flash[:notice] = "Opinia została usunięta!"
    else
      flash.now[:alert] = "Nie można usunąć opinii!"
    end

    redirect_to admin_opinions_path
  end

  private

  def no_record_handler
    flash[:alert] = "Nie znaleziono takiej opinii"
    redirect_to admin_opinions_path
  end
end

app/controllers/v1/opinions_controller.rb
class V1::OpinionsController < V1::BaseController

  before_filter :opinion_params, only: [:create, :update]
  expose(:report) { Report.find(params[:report_id]) }
  expose(:opinion) { report.opinions.where(id: params[:id]).first || report.opinions.create(opinion_params) }
  expose(:opinions) { report.opinions.order("created_at DESC") }

  before_filter :cookie_enabled?, only: [:update]

  def index
    respond_with opinions
  end

  def show
    respond_with opinion
  end

  def create
    respond_with opinion
  end

  def update
    if has_cookie?('opinion', opinion.id)
      forbidden_request
    else
      opinion.rate!(opinion_params[:key])
      set_cookie('opinion', opinion.id)

      respond_with opinion
    end
  end

  private

  def opinion_params
    begin
      params.require(:opinion).permit(:id, :key, :title, :description, :positives, :negatives)
    rescue ActionController::ParameterMissing
      unprocessable_entity
    end
  end
end

app/controllers/v2/opinions_controller.rb
class V2::OpinionsController < V2::BaseController

  before_filter :opinion_params, only: [:create, :update]
  expose(:report) { Report.find(params[:report_id]) }
  expose(:opinion) { report.opinions.where(id: params[:id]).first || report.opinions.create(opinion_params) }
  expose(:opinions) { report.opinions.order("created_at DESC") }

  before_filter :cookie_enabled?, only: [:update]

  def index
    respond_with opinions
  end

  def show
    respond_with opinion
  end

  def create
    respond_with opinion
  end

  def update
    if has_cookie?('opinion', opinion.id)
      forbidden_request
    else
      opinion.rate!(opinion_params[:key])
      set_cookie('opinion', opinion.id)

      respond_with opinion
    end
  end

  private

  def opinion_params
    begin
      params.require(:opinion).permit(:id, :key, :title, :description, :positives, :negatives)
    rescue ActionController::ParameterMissing
      unprocessable_entity
    end
  end
end

app/views/admin/opinions/index.html.haml
%h2 Opinie
%table.table.table-striped
  %caption Opinie do zgłoszeń
  %thead
    %tr
      %th= sortable("Opinion", "id", "Nr")
      %th= sortable("Opinion", "title", "Tytuł")
      %th= sortable("Opinion", "description", "Treść")
      %th= sortable("Opinion", "created_at", "Utworzono")
      %th= sortable("Opinion", "positives", "Plusy")
      %th= sortable("Opinion", "negatives", "Minusy")
      %th= sortable("Opinion", "report_id", "Zgłoszenie")
      %th Akcje
  %tbody
    - opinions.each do |o|
      %tr
        %td= o.id
        %td= o.title
        %td= o.description
        %td= l o.created_at, format: "%d-%m-%Y %H:%M:%S"
        %td= o.positives
        %td= o.negatives
        %td= o.report_id
        %td
          = link_to "Usuń", admin_opinion_path(o.id), method: :delete, confirm: "Jesteś pewny? Usunięcie jest nieodwracalne!"
          %br
          = link_to "Edytuj zgłoszenie", edit_admin_report_path(o.report_id) if o.report_id.present?

= paginate opinions