config/routes.rb
Reporter::Application.routes.draw do

  namespace :v1 do
    resources :reports, only: [:create, :index, :show, :update] do
      resources :abuses, only: [:create]
      resources :opinions, only: [:create, :index, :show, :update]
    end
    resources :maps, only: [] do
      collection do
        get :border
      end
    end
    resources :categories, only: [:index]
  end

  namespace :admin do
    root to: 'reports#index'
    get 'logout', to: 'user_sessions#destroy', as: :logout
    get 'login', to: 'user_sessions#new', as: :login
    resources :user_sessions, only: [:create]
    resources :reports
    resources :opinions
    resources :abuses
    resources :categories
  end

  root to: 'home#index'
end

app/controllers/admin/abuses_controller.rb
# -*- encoding : utf-8 -*-
class Admin::AbusesController < Admin::AdminController

  expose(:abuses) { Abuse.order(sort_column("Abuse") + " " + sort_direction).page(params[:page] || 1).per(params[:per_page] || 10) }
  expose(:abuse)

  rescue_from ActiveRecord::RecordNotFound, with: :no_record_handler

  def destroy
    if abuse.destroy
      flash[:notice] = "Zgłoszenie nadużycia zostało usunięte!"
    else
      flash.now[:alert] = "Nie można usunąć zgłoszenia nadużycia!"
    end

    redirect_to admin_abuses_path
  end

  private

  def no_record_handler
    flash[:alert] = "Nie znaleziono takiego zgłoszenia nadużycia"
    redirect_to admin_abuses_path
  end
end

app/controllers/api/abuses_controller.rb
# -*- encoding : utf-8 -*-
class Api::AbusesController < Api::ApiController

  before_filter :find_report

  METHODS = [:spam, :duplicate, :content, :solved]

  METHOD_TO_TEXT = {
    METHODS[0] => "spamie",
    METHODS[1] => "duplikacie",
    METHODS[2] => "nieodpowiedniej treści",
    METHODS[3] => "rozwiązaniu problemu"
  }

  METHODS.each do |m|
    define_method(m) do
      @report.abuses << Abuse.new(:name => m.to_s)
      render_json :thanks => "Informacja o #{METHOD_TO_TEXT[m]} została wysłana do moderatorów."
    end
  end

  private

  def find_report
    @report = Report.find_by_id(params[:report_id])
  end
end

app/controllers/v1/abuses_controller.rb
class V1::AbusesController < V1::BaseController

  before_filter :abuse_params, only: [:create]

  expose(:report) { Report.find(params[:report_id]) }
  expose(:abuse) { report.abuses.create(abuse_params) }

  def create
    respond_with abuse
  end

  private

  def abuse_params
    begin
      params.require(:abuse).permit(:name)
    rescue ActionController::ParameterMissing
      unprocessable_entity
    end
  end
end

app/controllers/v2/abuses_controller.rb
class V2::AbusesController < V2::BaseController

  before_filter :abuse_params, only: [:create]

  expose(:report) { Report.find(params[:report_id]) }
  expose(:abuse) { report.abuses.create(abuse_params) }

  def create
    respond_with abuse
  end

  private

  def abuse_params
    begin
      params.require(:abuse).permit(:name)
    rescue ActionController::ParameterMissing
      unprocessable_entity
    end
  end
end

app/views/admin/abuses/index.html.haml
%h2= t("views.admin.abuses.index.header")
%table.table.table-striped
  %caption= t("views.admin.abuses.index.caption")
  %thead
    %tr
      %th= sortable("Abuse", "id", t("views.admin.abuses.index.col_id"))
      %th= sortable("Abuse", "created_at", t("views.admin.abuses.index.col_created_at"))
      %th= sortable("Abuse", "report_id", t("views.admin.abuses.index.col_report_id"))
      %th= t("views.admin.abuses.index.col_reason")
      %th= t("views.admin.abuses.index.col_actions")
  %tbody
    - abuses.each do |a|
      %tr
        %td= a.id
        %td= l a.created_at, format: "%d-%m-%Y %H:%M:%S"
        %td= a.report_id
        %td= a.reason
        %td
          = link_to t("views.admin.abuses.index.delete_abuse"), admin_abus_path(a.id), method: :delete, confirm: t("views.admin.abuses.index.delete_confirmation")
          %br
          = link_to t("views.admin.abuses.index.edit_report"), edit_admin_report_path(a.report_id)
          %br
          = link_to t("views.admin.abuses.index.delete_report"), admin_report_path(a.report_id), method: :delete, confirm: t("views.admin.abuses.index.delete_confirmation")

= paginate abuses