config/routes.rb
Reporter::Application.routes.draw do

  namespace :v1 do
    resources :reports, only: [:create, :index, :show, :update] do
      resources :abuses, only: [:create]
      resources :opinions, only: [:create, :index, :show, :update]
    end
    resources :maps, only: [] do
      collection do
        get :border
      end
    end
    resources :categories, only: [:index]
  end

  namespace :admin do
    root to: 'reports#index'
    get 'logout', to: 'user_sessions#destroy', as: :logout
    get 'login', to: 'user_sessions#new', as: :login
    resources :user_sessions, only: [:create]
    resources :reports
    resources :opinions
    resources :abuses
    resources :categories
  end

  root to: 'home#index'
end

app/models/category.rb
# -*- encoding : utf-8 -*-
class Category < ActiveRecord::Base

  validates_presence_of :unique_id
  has_many :reports

  def image
    "categories/#{unique_id}.png"
  end

  def title
    I18n.t("models.category.#{unique_id}.title")
  end

  def description
    I18n.t("models.category.#{unique_id}.description")
  end
end

app/controllers/admin/categories_controller.rb
# -*- encoding : utf-8 -*-
class Admin::CategoriesController < Admin::AdminController

  expose(:categories) { Category.order(sort_column("Category") + " " + sort_direction).page(params[:page]).per(10) }
  expose(:category) { Category.find(params[:id]) }

  rescue_from ActiveRecord::RecordNotFound, with: :no_record_handler

  def update
    if category.update_attributes(category_params)
      flash[:notice] = "Kategoria została zaktualizowana!"
      redirect_to admin_categories_path
    else
      flash[:alert] = "Wystąpił problem. Sprawdź dane formularza."
      render :edit
    end
  end

  def destroy
    if category.destroy
      flash[:notice] = "Kategoria została usunięta!"
    else
      flash[:alert] = "Nie można usunąć zgłoszenia!"
    end

    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:unique_id)
  end

  def no_record_handler
    flash[:alert] = "Nie znaleziono takiej kategorii"
    redirect_to admin_categories_path
  end
end

app/controllers/v1/categories_controller.rb
class V1::CategoriesController < V1::BaseController

  expose(:categories) { Category.order(:created_at) }
end

app/views/admin/categories/edit.html.haml
%h2 Edytuj kategorię

= semantic_form_for category, url: admin_category_path(category.id), format: :html, class: 'form-signin', method: :put do |f|
  %li.icon
    %label.label Ikona kategorii
    = image_tag "categories/#{category.unique_id}.png", alt: "Ikona kategorii", width: 24
  = f.input :unique_id, label: "Unikalna nazwa", input_html: {disabled: "true"}
  = f.submit value: "Zapisz zmiany", class: "btn btn-large btn-primary"

app/views/admin/categories/index.html.haml
%h2= t("views.admin.categories.index.header")
%table.table.table-striped
  %caption= t("views.admin.categories.index.caption")
  %thead
    %tr
      %th= sortable("Category", "id", t("views.admin.categories.index.col_id"))
      %th= sortable("Category", "title", t("views.admin.categories.index.col_title"))
      %th= sortable("Category", "description", t("views.admin.categories.index.col_description"))
      %th= sortable("Category", "created_at", t("views.admin.categories.index.col_created_at"))
      %th= sortable("Category", "unique_id", t("views.admin.categories.index.col_unique_id"))
      %th= t("views.admin.categories.index.col_amount")
      %th= t("views.admin.categories.index.col_icon")
      %th= t("views.admin.categories.index.col_actions")
  %tbody
    - categories.each do |c|
      %tr
        %td= c.id
        %td= c.title
        %td= c.description
        %td= l c.created_at, format: "%d-%m-%Y %H:%M:%S"
        %td= c.unique_id
        %td= c.reports.count
        %td
          = image_tag c.image, alt: c.title, width: 75
        %td
          = link_to t("views.admin.categories.index.edit_category"), edit_admin_category_path(c.id)

= paginate categories