config/routes.rb
Reporter::Application.routes.draw do

  namespace :v1 do
    resources :reports, only: [:create, :index, :show, :update] do
      resources :abuses, only: [:create]
      resources :opinions, only: [:create, :index, :show, :update]
    end
    resources :maps, only: [] do
      collection do
        get :border
      end
    end
    resources :categories, only: [:index]
  end

  namespace :admin do
    root to: 'reports#index'
    get 'logout', to: 'user_sessions#destroy', as: :logout
    get 'login', to: 'user_sessions#new', as: :login
    resources :user_sessions, only: [:create]
    resources :reports
    resources :opinions
    resources :abuses
    resources :categories
  end

  root to: 'home#index'
end

app/views/admin/layouts/_flash.html.haml
- if flash.present?
  - if flash[:alert].present?
    #flash.alert
      = image_tag "flash_alert.png", alert: "Wystąpił błąd!"
      = flash[:alert]
  - elsif flash[:notice].present?
    #flash.notice
      = image_tag "flash_notice.png", alert: "Wszystko OK!"
      = flash[:notice]

app/views/admin/layouts/_top_bar.html.haml
.navbar.navbar-inverse.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar{'data-toggle' => 'collapse', 'data-target' => '.nav-collapse'}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.brand{href: admin_root_path}
        SZS-Poznań
      .nav-collapse.collapse
        %ul.nav
          %li{class: (controller_name == "reports" ? 'active' : '')}
            = link_to "Zgłoszenia", admin_reports_path
          %li{class: (controller_name == "categories" ? 'active' : '')}
            = link_to "Kategorie", admin_categories_path
          %li{class: (controller_name == "opinions" ? 'active' : '')}
            = link_to "Opinie", admin_opinions_path
          %li{class: (controller_name == "abuses" ? 'active' : '')}
            = link_to "Nadużycia", admin_abuses_path

        %ul.nav.pull-right
          %li
            = link_to "Wyloguj", admin_logout_path

app/views/admin/layouts/admin.html.haml
!!!
%html
  %head
    %title System Zgłaszania Szkód - Poznań - Panel administracyjny
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application, :media => "all"
  %body{class: "admin_namespace #{controller_path.gsub('/','_')}_controller #{action_name}_action", data: {view_name: "Admin"}}
    = render 'admin/layouts/top_bar'
    %section.content
      = render 'admin/layouts/flash'
      = yield

app/views/admin/layouts/new_user_session.html.haml
!!!
%html
  %head
    %title System Zgłaszania Szkód - Poznań
    = stylesheet_link_tag :application, media: "all"
    = javascript_include_tag :application, media: "all"
  %body{class: "#{controller_name}_controller #{action_name}_action", data: {view_name: "#{controller_name.classify}"}}
    %h2
      Logowanie

    = render "admin/layouts/flash"

    = semantic_form_for @user_session, url: admin_user_sessions_path, class: 'form-signin', method: :post do |f|
      = f.input :login, label: false, required: true, placeholder: "Login"
      = f.input :password, label: false, required: true, placeholder: "Hasło"
      = f.submit value: "Zaloguj", class: "btn btn-large btn-primary"